service: twitter-bots

provider:
  name: aws
  runtime: python3.8

functions:
  bot-handler:
    handler: handler.main
    events:
      - schedule: rate(2 hours)

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: non-linux
